### PR TITLE
Defer bug report processing

### LINKED ISSUE #18: Defer bug report processing
Currently, sending bug reports requires a network connection. If a network connection is not available, an error is thrown and the user will need to send the report again at a later time. 

This proposal is to allow the SDK to handle the deferment for the user so that even if there is no network connection, we will persist the request and try again later. 

This will consequently resolve #4 and also not require the user to stick around while the bug report is being uploaded.

### PR DESCRIPTION
**Pull request by alexfu**
Resolves #18 and #4. The new bug report processing functionality will use `JobScheduler` on devices running Lollipop or above. Everything below will fallback to using a standard `IntentService` (`SubmitReportLegacyService`).

For Lollipop and above devices, `JobScheduler` will reschedule jobs that fail due to a network loss. When using the `SubmitReportLegacyService`, if a bug report submission fails due to a network loss, it will be retried upon the next Buglife initialization (usually when the app opens again).

### CODE REVIEW

File: src/main/java/com/buglife/sdk/BugReporterImpl.java [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+            reportWithLegacy(report);
+        }
+    }
+
+    private void reportWithLegacy(Report report) {
+        try {
+            String jsonReport = report.toJSON().toString();
+            SubmitReportLegacyService.start(mContext, jsonReport);
+        } catch (JSONException e) {
+            Log.e("Failed to encode report!", e);
```
Comment (schukin) [inline src/main/java/com/buglife/sdk/BugReporterImpl.java]: Can we bubble up this error somehow?

Comment (alexfu) [reply src/main/java/com/buglife/sdk/BugReporterImpl.java]: @schukin Do you mean surfacing this error to the UI? We could display a Toast or re-throw the exception. My initial thought would be to re-throw since the having a badly formatted report would be a pretty serious error.

File: src/main/java/com/buglife/sdk/reporting/SubmitReportLegacyService.java [hunk 2]
```diff
@@ -0,0 +1,175 @@
...
+
+    @Override public void onCreate() {
+        super.onCreate();
+        mTask = new SubmitReportTask(getApplicationContext());
+    }
+
+    @Override protected void onHandleIntent(@Nullable Intent intent) {
+        File cacheFile = getReportsCacheFile(getApplicationContext());
+        if (!cacheFile.exists()) {
+            Log.i("Reports cache file doesn't exist! No reports to submit.");
```
Comment (schukin) [inline src/main/java/com/buglife/sdk/reporting/SubmitReportLegacyService.java]: Whenever I try to submit a report on my KitKat device, I see this get logged & my bug report is never actually submitted. It seems the `reports` directory for legacy submission is never actually created, so this method returns early. Before I went ahead and changed anything, I wanted to verify that the intent here (no pun intended) is to submit the "current" bug report, as well as all cached bug reports?

**Review by schukin — CHANGES_REQUESTED** [review]
This is *awesome*. Love seeing `BugContext` split into `SessionSnapshot` & `DeviceSnapshot` too 👌 Just two questions before I merge.

File: src/main/java/com/buglife/sdk/BugReporterImpl.java (hunk 1 above)
Comment (schukin) [reply src/main/java/com/buglife/sdk/BugReporterImpl.java]: Yeah, we should surface this error to the UI. That way when users encounter it, they at least have a vague clue that something went wrong and can help us figure it out. I would think it'd make sense to re-throw the exception at this level. Up the chain, I think we'd either want to throw a RuntimeException & let the app crash, or show a Toast so the user knows something went wrong. Thoughts?

File: src/main/java/com/buglife/sdk/reporting/SubmitReportLegacyService.java (hunk 2 above)
Comment (alexfu) [reply src/main/java/com/buglife/sdk/reporting/SubmitReportLegacyService.java]: @schukin This is a good catch. I had changed the behavior slightly so this check is no longer valid.

File: src/main/java/com/buglife/sdk/BugReporterImpl.java (hunk 1 above)
Comment (alexfu) [reply src/main/java/com/buglife/sdk/BugReporterImpl.java]: @schukin would you be opposed to doing both, throwing the exception and showing a toast here?

Comment (schukin) [reply src/main/java/com/buglife/sdk/BugReporterImpl.java]: @alexfu that sounds reasonable 👍

**Comment by alexfu** [comment]
@schukin updated to address changes.

**Comment by schukin** [comment]
w00t 🤘
